spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234
  sql:
    init:
      mode: always

server:
  port: 8090
